[package]
name = "kube"
version = "0.1.0"
authors = ["dannypsnl <dannypsnl@gmail.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "*"
